### ISSUE TITLE
Add 2D alpha shapes

### ISSUE THREAD

**Issue by mrzv** [mrzv/diode#1]
CGAL doesn't provide the necessary filtration, so we'll have to lift the code from Dionysus 1.

**Comment by xibeisiber** [comment]
yes. Dionysus 1 can't be compiled successfully on my computer(saying "CGAL/Periodic_3_Delaunay_triangulation_traits_3.h" is missing). Dionysus 2 and Diode work fine, but the 2D alpha is missing....
Thanks for your work!!! @mrzv
