### ISSUE TITLE
building error on CentOS

### ISSUE THREAD

**Issue by perligent** [mrzv/diode#4]
When `cmake ..`
`-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- __cplusplus is 201402
--   --> Do not link with Boost.Thread
-- Found Boost 1.70.0 at /share/home/yjiang/boost/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED
-- Found boost_headers 1.70.0 at /share/home/yjiang/boost/lib/cmake/boost_headers-1.70.0
-- Boost 1.48 found.
-- Boost include dirs: 
-- Boost libraries:    
-- Build type: Release
-- USING CXXFLAGS = ' -O3 -DNDEBUG'
-- USING EXEFLAGS = ' '
-- Targetting Unix Makefiles
-- Using /usr/local/bin/g++ compiler.
-- Requested component: MPFR
-- Requested component: GMP
-- Found PythonInterp: /share/home/yjiang/anaconda3/bin/python3.7 (found version "3.7") 
-- Found PythonLibs: /share/home/yjiang/anaconda3/lib/libpython3.7m.so
-- pybind11 v2.1.1
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- Performing Test HAS_CPP11_FLAG
-- Performing Test HAS_CPP11_FLAG - Success
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Failed
-- LTO disabled (not supported by the compiler and/or linker)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CGAL::CGAL
    linked by target "generate_periodic_alpha_shape" in directory /share/home/yjiang/Downloads/diode/examples
    linked by target "generate_alpha_shape" in directory /share/home/yjiang/Downloads/diode/examples
    linked by target "generate_weighted_alpha_shape" in directory /share/home/yjiang/Downloads/diode/examples
    linked by target "diode" in directory /share/home/yjiang/Downloads/diode/bindings/python

-- Configuring incomplete, errors occurred!
See also "/share/home/yjiang/Downloads/diode/build/CMakeFiles/CMakeOutput.log".
See also "/share/home/yjiang/Downloads/diode/build/CMakeFiles/CMakeError.log".`

Any help is greatly appreciated.

**Comment by mrzv** [comment]
It looks like you are missing CGAL. Also it's strange that your Boost headers are version 1.70, but your libraries are version 1.48.
