### ISSUE TITLE
Alha shape parameter

### ISSUE THREAD

**Issue by unverciftci** [mrzv/diode#5]
Hi,
Thank you for sharing your software, it is very handy to me. 
Is it possible to fix the alpha shape parameter?
Best wishes, Unver

**Comment by mrzv** [comment]
I'm not sure I understand what you are asking. Are you looking for something other than:
```
f = diode.fill_alpha_shapes(...)
f2 = [x for x in f if x[1] <= .5]
```

**Comment by unverciftci** [comment]
It finds the optimal alpha value by default. Can we change to another alpha value?

**Comment by mrzv** [comment]
Can you write more than a sentence about what you are after? What is "it" in your message? What is the optimal alpha value? The code computes the full alpha shape filtration. You can take any subset of it that you want.

**Comment by unverciftci** [comment]
Alpha shape has a radius which is called the alpha value. CGAL can both compute the alpha shape for an alpha value given by the user or it can find the optimal alpha radius by default. Alpha is a parameter.

**Comment by mrzv** [comment]
And what is your question? Diode computes the entire filtration, i.e., for every simplex it reports the alpha value at which it would enter the complex. The code snippet I gave above produces the alpha shape for a specific value (`.5` in that snippet).

**Comment by unverciftci** [comment]
By looking at an output I see what you mean. Thank you.

**Comment by mrzv** [comment]
Ok, then I'll close this issue. Feel free to reopen, if needed.
