### ISSUE TITLE
Compatibility issue with CGAL v5

### ISSUE THREAD

**Issue by Iain-S** [mrzv/diode#7]
## The issue

Diode requires CGAL.  The easiest way for most people to get CGAL is via a package manager.  For example, I did

```
sudo apt install libcgal-dev
```

On Ubuntu 20, this currently gives you **libcgal-dev 5.0.2-3**.

CGAL versions 5.0 and above require C++14 (see [releases](https://github.com/CGAL/cgal/releases)) but the Diode CMakeLists.txt says

```
set                         (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```

This results in a slew of errors when calling `make` during the Diode build process.  E.g.

> /usr/include/CGAL/Lazy.h:108:30: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type; did you mean ‘enable_if’?

### 1

Diode appears to build OK with C++14.  It compiles and the tests in test_simple.py pass (I could not find any other tests to run).  Therefore, we could change the CMakeLists.txt to say

```
set                         (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
```

Or add some logic to work out which version of CGAL is being used.

### 2

If you do not want to build Diode with c++14, please specify in the README that Diode only supports C++11 and CGAL v4.

**Comment by mrzv** [comment]
I have no problem with C++14. I just haven't run into CGAL 5 yet. I'm pushing a fix. Thanks for reporting.
