### ISSUE TITLE
add to conda-forge

### ISSUE THREAD

**Issue by kjappelbaum** [mrzv/diode#9]
Hi @mrzv, 

would you be interested in/ok with having diode on conda-forge? If yes, I can go ahead and create the recipe. 

Cheers, 
Kevin

**Comment by mrzv** [comment]
Sure. That would be great.

**Comment by kjappelbaum** [comment]
made a first draft here https://github.com/conda-forge/staged-recipes/pull/19798

**Comment by mrzv** [comment]
Closing since this is now on conda-forge: https://anaconda.org/conda-forge/diode.
